# Example App Engine configuration for serving a static React app.
# This is optional — the default pipeline targets Cloud Run. Keep this file
# if you want to deploy to App Engine instead.

runtime: nodejs18
instance_class: F2

handlers:
  # Serve the production build's index.html for the app root and SPA routes
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/\1

automatic_scaling:
  min_instances: 0
  max_instances: 3